//
//  LiveTokenBar.swift
//  Minis
//
//  Feature #7 — Live token usage bar.
//
//  A one-line, self-contained readout for the chat composer:
//
//      ↑ 1.2k   ↓ 356   ·   34.2 tok/s              73%
//      ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ (thin context bar, optional)
//
//  Zero coupling: takes plain values, renders with stock SwiftUI only.
//  It reads nothing from the view model and owns no state, so the caller
//  decides both when it appears and what feeds it.
//

import SwiftUI

// MARK: - LiveTokenBar

/// Compact live token readout for the chat composer.
///
/// All inputs are plain values — the view is a pure function of them, which
/// keeps it trivially previewable and avoids any view-model coupling.
///
/// - Parameters:
///   - inputTokens: tokens attributed to the prompt / context side (↑).
///   - outputTokens: tokens generated by the assistant so far (↓).
///   - rate: current generation speed in tokens/second. The rate segment is
///     hidden while `rate <= 0` so an idle bar shows only the counts.
///   - contextFraction: context-window occupancy in `0...1`, or `nil` to hide
///     both the percentage and the thin progress bar.
public struct LiveTokenBar: View {

    public let inputTokens: Int
    public let outputTokens: Int
    public let rate: Double
    public let contextFraction: Double?

    public init(inputTokens: Int,
                outputTokens: Int,
                rate: Double,
                contextFraction: Double? = nil) {
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.rate = rate
        self.contextFraction = contextFraction
    }

    // MARK: Body

    public var body: some View {
        VStack(alignment: .trailing, spacing: 3) {
            HStack(spacing: 5) {
                Text("↑ \(TokenDisplayFormatter.formatTokens(inputTokens))")
                Text("↓ \(TokenDisplayFormatter.formatTokens(outputTokens))")

                if rate > 0 {
                    separator
                    Text(TokenDisplayFormatter.formatRate(rate))
                }

                Spacer(minLength: 8)

                if let contextFraction {
                    Text(TokenDisplayFormatter.formatContextFraction(contextFraction))
                        .foregroundStyle(contextTint)
                }
            }
            .font(.caption2)
            .foregroundStyle(.secondary)
            .monospacedDigit()
            .lineLimit(1)
            .minimumScaleFactor(0.8)

            if let contextFraction {
                ContextFractionBar(fraction: contextFraction, tint: progressTint)
            }
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 4)
        .frame(maxWidth: .infinity)
        // The line is decorative to VoiceOver; expose one readable sentence.
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(accessibilityText)
    }

    /// Middle dot used between the counts and the rate.
    private var separator: some View {
        Text("·")
            .foregroundStyle(.tertiary)
            .accessibilityHidden(true)
    }

    /// `true` when there is nothing worth showing yet — the caller can use this
    /// to skip inserting the bar at all.
    public var isEmpty: Bool {
        inputTokens <= 0 && outputTokens <= 0 && rate <= 0 && contextFraction == nil
    }

    // MARK: Colour

    /// Text tint for the percentage. Stays `.secondary` (as required) until
    /// the context is close to full, then warns in semantic colours that
    /// adapt to light/dark automatically.
    private var contextTint: Color {
        guard let f = contextFraction else { return .secondary }
        if f >= 0.90 { return .red }
        if f >= 0.75 { return .orange }
        return .secondary
    }

    /// Fill tint for the thin bar. Uses the accent colour in the normal range.
    private var progressTint: Color {
        guard let f = contextFraction else { return .accentColor }
        if f >= 0.90 { return .red }
        if f >= 0.75 { return .orange }
        return .accentColor
    }

    // MARK: Accessibility

    private var accessibilityText: String {
        var parts: [String] = [
            "Input \(inputTokens) tokens",
            "output \(outputTokens) tokens"
        ]
        if rate > 0 {
            parts.append("rate \(TokenDisplayFormatter.formatRate(rate))")
        }
        if let contextFraction {
            parts.append("context \(TokenDisplayFormatter.formatContextFraction(contextFraction)) full")
        }
        return parts.joined(separator: ", ")
    }
}

// MARK: - ContextFractionBar

/// Hairline progress bar for context-window occupancy.
private struct ContextFractionBar: View {
    let fraction: Double
    let tint: Color

    private var clamped: Double {
        guard fraction.isFinite else { return 0 }
        return min(max(fraction, 0), 1)
    }

    var body: some View {
        GeometryReader { geo in
            ZStack(alignment: .leading) {
                Capsule(style: .continuous)
                    .fill(Color.primary.opacity(0.10))
                Capsule(style: .continuous)
                    .fill(tint)
                    .frame(width: max(0, geo.size.width * clamped))
            }
        }
        .frame(height: 2)
        .accessibilityHidden(true)
    }
}

// MARK: - Preview

#if DEBUG
#Preview("LiveTokenBar") {
    VStack(spacing: 12) {
        LiveTokenBar(inputTokens: 1_200, outputTokens: 356, rate: 34.2)
        LiveTokenBar(inputTokens: 1_200, outputTokens: 356, rate: 34.2, contextFraction: 0.42)
        LiveTokenBar(inputTokens: 48_500, outputTokens: 9_120, rate: 0, contextFraction: 0.93)
        LiveTokenBar(inputTokens: 0, outputTokens: 0, rate: 0)
    }
    .padding(.vertical, 16)
}
#endif
